version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app  # Corrected path to ensure it matches the context
      - /app/node_modules
    working_dir: /app  # Ensures npm runs commands in the correct directory
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/TaskNest
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    working_dir: /app  # Ensures the backend runs commands in the correct directory

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always  # Ensures MongoDB restarts automatically if it fails

volumes:
  mongo_data:
